package com.example.TgBimBot.finalVariables.stikers;

import java.util.Arrays;
import java.util.List;

public class StepfatherStickers {

    public static final List<String> stepfatherStickers = Arrays.asList(
            "CAACAgQAAxkBAAIMA2aXdOi_Rzvi_z1ScQQmT89its8qAAI4GAACpvFxHr0jFUJQuylLNQQ",
            "CAACAgQAAxkBAAIMBmaXdQouQ3i-rgpW1kj099FLYeUUAALpCAACz8AQUicVeiQsEZKtNQQ",
            "CAACAgQAAxkBAAIMCWaXdRkOwS15l1PnHPGGIz_XdSkzAAI6GAACpvFxHpxgDmUegD90NQQ",
            "CAACAgQAAxkBAAIMDGaXdSwJb2LTzNVmywABxx6Es8p8cQACOxgAAqbxcR7RWjv3yaTBTzUE",
            "CAACAgQAAxkBAAIMD2aXdT2njWtW_dCoy8GIWXMqRqx7AAI8GAACpvFxHqlzeWrm-M94NQQ",
            "CAACAgQAAxkBAAIMF2aXdVHgx9ZATN22F2EN9cBSItmlAAI9GAACpvFxHisx191HEj04NQQ",
            "CAACAgQAAxkBAAIMHWaXdWGlQX0MvXfGIJlh1X5E4yp6AAI-GAACpvFxHugrc4qXakrtNQQ",
            "CAACAgQAAxkBAAIMJmaXdXCmE1UIuJUSgxzmjSlI3UbNAAI_GAACpvFxHiVJXTdoroFpNQQ",
            "CAACAgQAAxkBAAIMLGaXdX6gtjsG_qVm4mv57LrTP2X8AAJAGAACpvFxHmHN6ipaFu7yNQQ",
            "CAACAgQAAxkBAAIMNGaXdY9Po8CFJ7lHi7rlfm-diQzJAAJBGAACpvFxHve_Vurepc6QNQQ",
            "CAACAgQAAxkBAAIMOmaXdaArR6kUjhxzeeZBmxryirJ0AAJCGAACpvFxHtq2_AXlFpNxNQQ",
            "CAACAgQAAxkBAAIMQGaXda44WR7KFFU8qe3pEXYMJ2LEAAJDGAACpvFxHlwz1nu-y4A2NQQ",
            "CAACAgQAAxkBAAIMRmaXdbzEXZe2IKV7K0BsG76HfTssAAJEGAACpvFxHkme5rF-ZGWhNQQ",
            "CAACAgQAAxkBAAIMSWaXdcxG2SlutohOUYGuh525boC-AAJFGAACpvFxHnv9OIe_U9UlNQQ",
            "CAACAgQAAxkBAAIMTGaXddsI8m85MJVIP-ek2KvBivqEAAJGGAACpvFxHl3-GNaJ_mTvNQQ",
            "CAACAgQAAxkBAAIMT2aXdfLnUh1-5aK2YfBVCDCGTxw2AAJHGAACpvFxHmshc5ogsAH7NQQ",
            "CAACAgQAAxkBAAIMUmaXdgUH80XxLR4Eb2rGbtPprascAAJIGAACpvFxHtQaQ6rhbpooNQQ",
            "CAACAgQAAxkBAAIMVWaXdhU_O91VpzsUVO5ixshJ2_66AAJJGAACpvFxHvM6kPk-aBuuNQQ",
            "CAACAgQAAxkBAAIMWGaXdiQEjCy3M9bDAjoNEQABC8WX1wACShgAAqbxcR4QmgeRh4Kl_DUE",
            "CAACAgQAAxkBAAIMW2aXdjMta5cGKXZaqcXCVfQHchsXAAJLGAACpvFxHjXothFsaySONQQ",
            "CAACAgQAAxkBAAIMXmaXdkAhoJOsZu1vILNoc6N75eRjAAJMGAACpvFxHg1x_lvbf67MNQQ",
            "CAACAgQAAxkBAAIMYWaXdk-1mPOTS8cmeugeYkdw1cM_AAJNGAACpvFxHhd45sKDSC72NQQ",
            "CAACAgQAAxkBAAIMZGaXdl8Mv0sy9O1BfSdrHH5hYHJNAAJPGAACpvFxHs6ITZWMuUtFNQQ",
            "CAACAgQAAxkBAAIMZ2aXdm0-5vq4PRoSQIpgz9gumNw6AAKPGAACpvFxHj0ww84XmRXzNQQ",
            "CAACAgQAAxkBAAIMamaXdnoePKf46wJX2aKzb7zLW6s-AAKSGAACpvFxHnZ7BnVtwHWnNQQ",
            "CAACAgQAAxkBAAIMbWaXdoxzmBE8oPDL4IhjtkQVCZQCAAKQCAACJxsgUvrLOotuYIzINQQ",
            "CAACAgQAAxkBAAIMcGaXdqrUisBSCGtv_SwyPSYtAoucAAKRGAACpvFxHsYHyv5z1QaQNQQ",
            "CAACAgQAAxkBAAIMc2aXdra70Lslp80Z7oS2v04SrvNnAAJMCAAC0WEYUmM7uZq6kk8cNQQ",
            "CAACAgQAAxkBAAIMdmaXdsI9SRP3RS4fhAcSIdCmf4RMAAIDCwACm4IgUvgmFwzKC8JRNQQ",
            "CAACAgQAAxkBAAIMeWaXdtKLWCgBD9kRjIXtivyJaZ3VAAJQCQACtRxpUvtxaldB2SfHNQQ",
            "CAACAgQAAxkBAAIMfGaXduGSlwJXO6khyyGSieHvRXK4AAJ-DAACLI5oUmmxY6dKAAGsCDUE",
            "CAACAgQAAxkBAAIMf2aXdu7rp__Xk6vXY9IB4Xu-5STxAAIqDAACL2zJUqp_xA-xTaClNQQ",
            "CAACAgQAAxkBAAIMgmaXdvwRG2dd7MuUmewsu5BYqL9jAAJcCgACzhPwUIbQnESa0uPUNQQ",
            "CAACAgQAAxkBAAIMhWaXdxR7xXcj8S6bO3z40Vf8ESo-AAKpCAACII8RU-ic4PTDlMzlNQQ",
            "CAACAgQAAxkBAAIMiGaXdyWm9an_DdpuuXwAAV3BjnPUZwACDwoAAmIAAQhTt9W4hBhLiXc1BA",
            "CAACAgQAAxkBAAIMi2aXdzM0o9Ph52yq-TMcgAIuLKlcAALvCwAC4anBUyZJN24jSedwNQQ",
            "CAACAgQAAxkBAAIMjmaXd0UPCc5NluRReL4aO-W3IXGHAALOCwACTVvwUBcudpFfJO_8NQQ",
            "CAACAgQAAxkBAAIMkWaXd1SWog5fwCD5RSAhiLP9BD8mAALXCQACuCzoUAnGq6WjocdVNQQ",
            "CAACAgQAAxkBAAIMlGaXd2Lpz90UlFDPdDHiTEqR7a-FAAJOGAACpvFxHiDfIEB89xNiNQQ",
            "CAACAgQAAxkBAAIMl2aXd3HPO4ydVFOZ06AgmuYwZMVQAAJQGAACpvFxHs06JilGlxgVNQQ",
            "CAACAgQAAxkBAAIMmmaXd3-4eaNKWWbs1odK-EJNx9lsAAJRGAACpvFxHkWsFulfjdm4NQQ",
            "CAACAgQAAxkBAAIMnWaXd47pxsozyiAdlNMIlpSOafblAAJSGAACpvFxHtNw1agUhgktNQQ",
            "CAACAgQAAxkBAAIMoGaXd5y2Ha8KJxFFAAF6JEozgMRz7gACUxgAAqbxcR6y43MPcH8KjzUE",
            "CAACAgQAAxkBAAIMo2aXd6vix01TKQnS7lbtKj4RhjkEAAKOGAACpvFxHlZ9kbsr7IVuNQQ",
            "CAACAgQAAxkBAAIMpmaXd8Mn7AbYdSF6W0dc6wOpdUNpAAKQGAACpvFxHpO0sy-FW86hNQQ",
            "CAACAgQAAxkBAAIMqWaXd9LCotRnV9gYNc5EF-N69ml7AAKUCQACbH4hUl85AaZ-_TFaNQQ",
            "CAACAgQAAxkBAAIMrGaXd98Ro6cBDtbCuCWSU4XJE6ZxAAJkCgACiD_QUnSiAgU3_gUNNQQ",
            "CAACAgQAAxkBAAIMr2aXd-5FZLvEd0MfVw07TfBYUqGhAAJ_CAACoSDpUGWbJFTen1B9NQQ",
            "CAACAgQAAxkBAAIMsmaXd_low9vF3ajoVFkj6ONV_HK8AAKLCwACbzCgUTmc3MK5MweFNQQ"
    );
}
